config/routes.rb
Rails.application.routes.draw do
  resources :comments
  root 'questions#index'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :questions do
    resources :comments
    member do
      get 'like_c' => 'comments#like'
      get 'link_c' => 'comments#like_link'
      get 'like' => 'questions#like'
      get 'link' => 'questions#like_link'
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :question
  belongs_to :user

  validates :body,presence: true

  acts_as_votable
end

app/models/question.rb
class Question < ApplicationRecord

  self.per_page = 5

  belongs_to :user
  has_many :comments
  validates :title, length: { minimum: 5,maximum: 60 }
  validates :content, length: { minimum: 5,maximum: 220 }
  acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :questions
  has_many :comments
  acts_as_voter

  after_commit :add_default_avatar, on: %i[create update]

  private(
    def add_default_avatar
      unless avatar.attached?
        avatar.attach(
          io: File.open(
            Rails.root.join('app', 'assets', 'images', 'default_profile.png')
          ), filename: 'default_profile.png',
          content_type: 'image/png')
      end
    end
  )
  def user_avatar
     if avatar.attached?
       avatar.variant(resize: '90x90!')
     else
       add_default_avatar
     end
  end


  attr_writer :login
    validate :validate_username

  def login
    @login || username || email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  helper_method :is_admin!
  private
    def is_admin!
      if current_user && current_user.admin
      else
        redirect_to root_path
      end
  end

  protected

  def configure_permitted_parameters
    added_attrs = [:avatar ,:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs

  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy like ]
  before_action :authenticate_user!, except: %i[index show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  respond_to :js, :html, :json

  def correct_user
    if user_signed_in? && @comment.user_id == current_user.id or current_user.try(:admin?)
    else
      redirect_to @question, notice: ">غير مصرح لك "
    end
  end

  def like
    if current_user.voted_for? @comment
      @comment.unliked_by current_user
    else
      @comment.liked_by current_user
    end
    redirect_back fallback_location: @question
    end

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @question=Question.find(params[:question_id])
    @comment = @question.comments.new(comment_params.merge(user_id: current_user.id,))

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @question, notice: "تم نشر التعليق بنجاح" }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    @question = Question.find_by_id @comment.question_id

    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @question, notice: "تم تعديل التعليق بنجاح" }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @question = Question.find_by_id @comment.question_id
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @question, notice: "تم حذف التعليق بنجاح" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :question_id, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[show edit update destroy like]
  before_action :authenticate_user!, except: %i[index show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  respond_to :js, :html, :json

  # GET /questions
  # GET /questions.json

  def index
    @q = Question.order('created_at DESC').paginate(page: params[:page]).ransack(params[:q])
    @questions = @q.result
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params.merge(user_id: current_user.id, created_by: current_user.username))
    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: "تم نشر الموضوع" }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: "تم تعديل الموضوع بنجاح" }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE questions
  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end

  def like
    if current_user.voted_for? @question
      @question.unliked_by current_user
    else
      @question.liked_by current_user
    end
    redirect_back fallback_location: @question
  end

  def correct_user
    if user_signed_in? && @question.user_id == current_user.id or current_user.try(:admin?)
      else
        redirect_to questions_path, notice: ">غير مصرح لك "
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:title, :content)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<% unless !comment.persisted? %>
  <div class="py-3 border-bottom comment comment-<%= comment.id%>">

    <div class="card text-right">
      <div class="row align-content justify-items">

        <div class="user_details col-auto ">
          <%= image_tag comment.user.user_avatar, class: 'rounded-circle position-relative top-50 start-50 translate-middle '%>
        </div>

        <div class="col">
          <div class="card-body">
            <p class="card-text"><%= comment.body %></p>
          </div>

          <div class="card-footer text-muted style="width="100rem;" >
            <small> نٌشِر منذ : <%= time_ago_in_words(comment.created_at) %> </small>
            <strong class="text-dark">بواسطة :  <%= comment.user.username %>  </strong>
            <% if user_signed_in? && comment.user_id == current_user.id or current_user.try(:admin?) %>
              <%= link_to "تعديل التعليق", edit_comment_path(comment), class: "btn btn-sm btn-outline-primary" %>
              <%= button_to "حذف التعليق" ,comment_path(comment),  method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-outline-danger" %>
            <%end %>
          </div>
        </div>
        <div class="user_details col-1">
          <div id='like-count'>
            <%=render 'comments/like', comment: comment, remote:true %>
          </div>
          <div id='like-link'>
            <div> <%=render 'comments/like_link', comment: comment, remote:true %></div>
          </div>

        </div>

      </div>
    </div>
  </div>



<% end %>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :body, class: "form-control", placeholder: "عنوان الموضوع" %>
  </div><br/>

  <div class="actions ">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_like.html.erb
<strong> التصويتات:<br/> <%= comment.get_upvotes.size %>   </strong>

app/views/comments/_like_link.html.erb
<% like = image_tag "Like.png", size: '30x30' %>
<% unlike = image_tag "unLike.png", size: '30x30' %>

<% vote_text = current_user&.voted_for?(comment)?  like : unlike %>
<%= link_to vote_text, like_c_question_path(comment),
            method: :put, remote: :true, class: 'like' %>

app/views/comments/edit.html.erb
<br/>

<h1>تعديل التعليق</h1>
<br/>
<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Question</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <%= image_tag comment.user.user_avatar, class: 'rounded-circle', size:'50x50' %>
        <td><%= comment.body %></td>
        <td><%= comment.question_id %></td>
        <td><%= comment.user_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/like.js.erb
$("#like-count").html("<%= j render 'comments/like', comment: comment %>");
$("#like-text").html("<%= j render 'comments/like_link', comment: comment %>");

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<div class="card" style="width: 79rem;">
  <div class="card-body">
    <%= image_tag @comment.user.user_avatar, class: 'rounded-circle '%>
    <br/>
    <H3><%= @comment.user.username %> </H3>
    <br/>

    <p class="card-text"><strong>المحتوى:<br/></strong>
      <%= @comment.body  %>
    </p>
    <%= link_to 'تعديل', edit_comment_path(@comment) %> |
    <%= link_to 'العودة',@question  %>

app/views/home/_header.html.erb
<nav class=" navbar navbar-expand-lg navbar-dark bg-secondary" dir="rtl">
  <div class="container-fluid">

    <%= link_to image_tag("Logo.png", width:'270px', height: '70px'), root_path , class:"navbar-brand" %>
    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
      <% if user_signed_in? %>
          <li class="nav-links" dir="rtl">
            <%= link_to "الملف الشخصي",  edit_user_registration_path, class:"nav-link border rounded" %>
          </li>

          <li class="nav-links" dir="rtl">
            <%= link_to "تسجيل الخروج",  destroy_user_session_path, method: :delete, class:"nav-link border rounded" %>
          </li>

      <% else %>

        <li class=" nav-links" dir="rtl">
          <%= link_to "للتسجيل", new_user_registration_path, class:"nav-link border rounded" %>
        </li>

        <li class="nav-links" dir="rtl">
          <%= link_to "تسجيل الدخول",new_user_session_path, class:"nav-link border rounded" %>
        </li>

    <% end %>

      <li class="nav-links" dir="rtl">
        <%= link_to "الصفحة الرئيسية",questions_path , class:"nav-link border rounded" %>
      </li>
    </ul>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent" >
    </div>

      <form  class="navbar-nav">
        <button class="btn btn-dark" type="submit">بحث</button>
        <%if @q%>
         <%= search_form_for @q do |f| %>
           <%= f.search_field :title_cont %>
         <%end %>
        <%end %>
      </form>

  </div>
</nav>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
<%= notice %>>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html >
<html lang='ar' dir="rtl">


<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
  <title>Zero-One</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>


</head>

<body class="bg">
<%= render 'home/header' %>
<div class="container">
  <% if notice %>
      <%=render 'layouts/alerts' %>
  <%end %>
<%= yield %>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
</body>


<footer class="Footer1"></footer>
</html>

app/views/questions/_form.html.erb
<%= form_with(model: question) do |form| %>
  <% if question.errors.any? %>

    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>
      <ul>
        <% question.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>

  <% end %>
  <br/>

  <div class="field">
    <%= form.text_field :title, class: "form-control", placeholder: "عنوان الموضوع" %>
  </div><br/>

  <div class="field">
    <%= form.text_area :content,  class: "form-control", placeholder: "محتوى الموضوع" %>
  </div>
  <div class="field">
    <% form.text_area :created_by, value: current_user.username %>
  </div>
  <br/>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/questions/_like.html.erb
<strong> التصويتات:<br/> <%= question.get_upvotes.size %>   </strong>

app/views/questions/_like_link.html.erb
<% like = image_tag "Like.png", size: '30x30' %>
<% unlike = image_tag "unLike.png", size: '30x30' %>

<% vote_text = current_user&.voted_for?(question) ?  like : unlike %>
<%= link_to vote_text, like_question_path(question),
            method: :put, remote: :true, class: 'like' %>

app/views/questions/edit.html.erb
<br/>
<h1>تعديل الموضوع</h1>


<%= render 'form', question: @question %>

<%= link_to 'اظهار', @question %> |
<%= link_to 'للعودة', questions_path %>

app/views/questions/index.html.erb
<html lang='ar' dir="rtl">

    <br/><br/>

    <% if user_signed_in? %>
    <div class="form-group">
      <%= image_tag current_user.user_avatar, class: 'rounded-circle'%>
      <h3> مرحبًا <%= current_user.username %></h3>
    </div>
    <%end %>
<br/>

  <div class="card text-light bg-dark">
     <h1 class="card-header"> قائمة المواضيع </h1>
  </div>

    <br/>

      <% if user_signed_in? %>
  <%= link_to 'سؤال جديد', new_question_path, class:"btn btn-dark" %>
      <% else %>
  <%= link_to "سؤال جديد", new_user_session_path, class:"btn btn-dark" %>
      <% end %>
      <div class="digg_pagination">
        <%= will_paginate @questions, :container => false %>
      </div>

      <br>
    <% @questions.each do |question|  %>
  <div class="card text-right">
    <div class="row align-content justify-items">

        <div class="user_details col-auto rows-3 ">
        <%= image_tag question.user.user_avatar, class: 'rounded-circle position-relative top-50 start-50 translate-middle '%>
      </div>

      <div class="col">
        <div class="card-title" >
          <h4><%=link_to question.title, question, class: 'card-title-text '%>   </h4>
        </div>
        <div class="card-body">
          <p class="card-text"><%= question.content %></p>
        </div>
        <div class="card-footer text-muted style=" width="90rem; " >
          <small> نٌشِر منذ : <%= time_ago_in_words(question.created_at) %> </small>
          <td><%= link_to 'اظهار', question %></td>
          <strong class="text-dark">بواسطة :  <%= question.user.username %>  </strong>
          <% if user_signed_in? && question.user_id == current_user.id or current_user.try(:admin?) %>
            <td><%= link_to 'تعديل', edit_question_path(question), class: "btn btn-outline-primary btn-sm" %></td>
            <td><%= button_to 'حذف', question_path(question), data: {confirm: "Are you sure?"}, method: :delete,  class: "btn btn-outline-danger btn-sm" %></td>
          <%end %>
        </div>
      </div>

      <!-- نظام التصويت -->
      <div class="user_details col-1">
        <div class="position-relative top-50 start-50 translate-middle" style= hight:10rem>
          <div id='like-count'>
            <%=render 'questions/like', question: question %>
          </div>
          <div id='like-link'>
            <div> <%=render 'questions/like_link', question: question %></div>
          </div>
          <p> التعليقات: <%=question.comments.count%> </p>
        </div>
      </div>
    </div>
  </div>
  <br/><br>
<%end %>

<div class="digg_pagination">
  <%= will_paginate @questions, :container => false %>
</div>
<br>
</html>

app/views/questions/like.js.erb
$('.liked-btn').on('ajax:success', function(){
    $(this).parent().parent().find('.like-count').html('<%= @question.get_likes.size %> &128591');
    $(this).closet('.liked-btn').html('Like');
});

$('.like-btn').on('ajax:success', function(){
    $(this).parent().parent().find('.like-count').html('<%= @question.get_likes.size %> &128591');
    $(this).closet('.like-btn').html('Liked');
});

app/views/questions/new.html.erb
<br/>
<h1>اضافة موضوع جديد</h1>

<%= render 'form', question: @question %>

<%= link_to 'للعودة', questions_path %>

app/views/questions/show.html.erb
<br/>  <br/>
<div class="card" style="width: 79rem;">
  <div class="card-body">
    <%= image_tag @question.user.user_avatar, class: 'rounded-circle '%>
    <H3><%= @question.user.username %> </H3>

    <h5 class="card-title"><strong>العنوان:</strong>
      <%= @question.title %>
    </h5>
    <p class="card-text"><strong>المحتوى:<br/></strong>
      <%= @question.content %>
    </p>
    <%= link_to 'تعديل', edit_question_path(@question) %> |
    <%= link_to 'العودة', questions_path %>
   <p>كتبت بواسطة <%= @question.user.username %> </p>

        <!-- نظام التصويت-->
    <div id='like-count'>
      <%=render 'questions/like', question: @question %>
    </div>
    <div id='like-link'>
      <%=render 'questions/like_link', question: @question %>
    </div>
  </div>
</div>
<br/>

      <!-- التعليقات-->
<div class="card mb-3">
  <div class="card-body">
  <%= form_with(model: [@question, @question.comments.build]) do |f| %>

      <div class="form-group">
        <%= f.text_area :body, class: 'form-control', placeholder: 'إضافة رد جديد' %>
      </div><br/>
      <%= f.submit 'إرسال', class: 'btn btn-primary' %>
      </div>
  <% end %>

    </div>
<div class="card mb-3">
<div class="card-header bg-info">
  <h4 class="font-weight-bold">التعليقات</h4>
</div>
  <br/>
  <h5>  عدد التعليقات: <%=@question.comments.count%>  </h5>
  <div class="card-body">
<%= render @question.comments %>
</div>
</div>